### PR TITLE
Support for go1.21, bump dependencies

### PR DESCRIPTION
**Pull request by gaby**
- Added go 1.21 to matrix strategy
- Update dependencies/cleaned go.sum file

### CODE REVIEW

**Comment by gaby** [comment]
@hengfeiyang Small PR to take care of outdated dependencies. Thanks!

**Review by hengfeiyang — APPROVED** [review]

**Comment by hengfeiyang** [comment]
@gaby Thank you.

**Comment by gaby** [comment]
@hengfeiyang Can you publish a new release? Thanks! 💪

**Comment by hengfeiyang** [comment]
Done

**Comment by gaby** [comment]
Thanks!

**Pull request merged**
